#@ load("@ytt:base64", "base64")
#@ load("@ytt:data", "data")
#@ load("@ytt:json", "json")

---
apiVersion: v1
kind: Secret
metadata:
  name: image-registry-credentials
  namespace: cf-system
type: kubernetes.io/dockerconfigjson
data:
  #@ system_registry_auth = base64.encode("{}:{}".format(data.values.system_registry.username, data.values.system_registry.password))
  #@ system_registry_creds = {"username": data.values.system_registry.username, "password": data.values.system_registry.password, "auth": system_registry_auth}
  .dockerconfigjson: #@ base64.encode(json.encode({"auths": {data.values.system_registry.hostname: system_registry_creds}}))
